$pdf_mode = 1;
$bibtex_use = 1;
ensure_path('TEXINPUTS', './shared');
$pdflatex = 'lualatex --synctex=1 --interaction=nonstopmode --shell-escape %O %S';
$out_dir = 'build';

@default_files = ('*.beamer.tex', '*.article.tex');

$clean_ext = 'nav snm vrb';
